language: csharp
solution: ABCNet.sln
dist: trusty
sudo: required
matrix:
  include:
    - dotnet: 1.0.0-preview2-003131 # latest available on travis (Microsoft .NET Core 1.0.1 - SDK 1.0.0 Preview 2)
      mono: none
      env: DOTNETCORE=1
